//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// I-RES2.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_IRES2TYPE                   130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDB_BITMAP1                     310
#define IDD_DIALOG_MAIN_TOOLBAR         310
#define IDB_BITMAP2                     311
#define IDD_DIALOG1                     312
#define IDD_DIALOG_SELECT_SECTIONS      312
#define IDD_DIALOG_PROGRESS             314
#define IDD_DIALOG_DEFINE_INP           316
#define IDB_BITMAP_NEW                  317
#define IDD_DIALOG_1                    318
#define IDB_BITMAP_DATUM                318
#define IDB_BITMAP_NORMAL               319
#define IDD_DIALOG_2                    320
#define IDB_BITMAP_ROT                  320
#define IDB_BITMAP_TRANS                321
#define IDD_DIALOG_DRAFTSECTION         322
#define IDD_DIALOG_CROSSSECTION         323
#define IDD_DIALOG_SECTION_TOOLBAR      324
#define IDB_BITMAP_CALC                 325
#define IDD_DIALOG_CONDITION            325
#define IDB_BITMAP_TOOLBAR              326
#define IDD_DIALOG_MATERIAL             326
#define IDD_DIALOG_CREATE_JOB           328
#define IDD_DIALOG_OUTPUT_TOOLBAR       329
#define IDR_TOOLBAR2                    331
#define IDD_DIALOG_EXCEL                333
#define IDB_BITMAP_EXCEL                336
#define IDB_BITMAP_GRAPH                337
#define IDD_DIALOG_TRANSLATE            338
#define IDB_BITMAP_HOR                  340
#define IDB_BITMAP_HOR_PT               341
#define IDB_BITMAP_VER                  342
#define IDB_BITMAP_VER_PT               343
#define IDD_DIALOG_CHART                346
#define IDB_BITMAP_SETUNIT              348
#define IDR_POPUP_ANALYSIS              350
#define IDD_DIALOG_CALC                 351
#define IDC_LIST1                       1000
#define IDC_MFCBUTTON_CLEAR             1000
#define IDC_PROGRESS1                   1001
#define IDC_MFCBUTTON_TRANS             1001
#define IDC_CHECK_POINT                 1001
#define IDC_STATIC_STATUS               1002
#define IDC_MFCBUTTON_ROT               1002
#define IDC_CHECK_AXIS                  1002
#define IDC_TAB1                        1003
#define IDC_MFCBUTTON_DATUM             1003
#define IDC_EDIT_DRAFT                  1003
#define IDC_SPIN1                       1004
#define IDC_MFCBUTTON_NORMAL            1004
#define IDC_EDIT_POINT_DISTANCE         1004
#define IDC_EDIT_INITIAL_STRENGTH       1005
#define IDC_EDIT_AXIS_DISTANCE          1005
#define IDC_MFCBUTTON_SETUNIT           1005
#define IDC_SPIN2                       1006
#define IDC_MFCBUTTON_CALCULATE         1006
#define IDC_MFCBUTTON_CALC              1006
#define IDC_EDIT_MAXIMUM_STRENGTH       1007
#define IDC_EDIT_DRAFT2                 1007
#define IDC_SPIN3                       1008
#define IDC_EDIT_DRAFT3                 1008
#define IDC_EDIT_STRENGTH_INCREMENTS    1009
#define IDC_SPIN4                       1010
#define IDC_EDIT_FRICTION_COEFF         1011
#define IDC_SPIN5                       1012
#define IDC_EDIT_INITIAL_THICKNESS      1013
#define IDC_SPIN6                       1014
#define IDC_EDIT_MAXIMUM_THICKNESS      1015
#define IDC_SPIN7                       1016
#define IDC_EDIT_THICKNESS_INCREMENTS   1017
#define IDC_EDIT_MAXIMUM_THICKNESS2     1017
#define IDC_SPIN8                       1018
#define IDC_EDIT_LENGTH                 1019
#define IDC_EDIT_E_SIGMA                1019
#define IDC_SPIN9                       1020
#define IDC_EDIT_MODELED_DEPTH          1020
#define IDC_EDIT_MODELED_BREADTH        1021
#define IDC_EDIT_ICE_DENSITY            1021
#define IDC_SPIN10                      1022
#define IDC_EDIT_DESIGN_DRAFT           1022
#define IDC_EDIT_INITIAL_SPEED          1023
#define IDC_EDIT_WATER_DENSITY          1023
#define IDC_EDIT_MAXIMUM_SPEED          1024
#define IDC_EDIT_SPEED_INCREMENTS       1025
#define IDC_CHECK_VIEW_DRAFT_PLANE      1026
#define IDC_EDIT_THICKNESS_INCREMENTS2  1026
#define IDC_CHECK_VIEW_DRAFT_POINTS     1027
#define IDC_CHECK_VIEW_CROSS_PLANE      1028
#define IDC_RADIO_CONSTANT              1028
#define IDC_CHECK_VIEW_CROSS_POINTS     1029
#define IDC_RADIO_PARAMETRIC            1029
#define IDC_STATIC_SHIP_SPEED           1031
#define IDC_STATIC_INC_SHIP_SPEED       1032
#define IDC_STATIC_MAX_THICK            1033
#define IDC_STATIC_THICK_INC            1034
#define IDC_EDIT1                       1035
#define IDC_GRID1                       1042
#define IDC_STATIC_CAPTION              1043
#define IDC_BUTTON_OK                   1044
#define IDC_CHECK_UNIT_M                1045
#define IDC_CHECK_UNIT_MM               1046
#define IDC_STCHARTCONTAINER            1046
#define IDC_MFCBUTTON_EXCEL1            1047
#define IDC_MFCBUTTON_GRAPH1            1048
#define IDC_MFCBUTTON_EXCEL2            1049
#define IDC_MFCBUTTON_GRAPH2            1050
#define IDC_GRID                        1051
#define IDC_STATIC_1                    1052
#define IDC_STATIC_2                    1053
#define IDC_EDIT_1                      1054
#define IDC_EDIT_2                      1055
#define IDC_BUTTON_LOAD_TXT             1056
#define IDC_EDIT_3                      1057
#define IDC_BUTTON_SET_ROWS             1058
#define IDC_BUTTON_DO_CALC              1059
#define IDC_GRID2                       1060
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON_OPEN                  32771
#define ID_BUTTON_SAVE                  32772
#define ID_BUTTON_SAVE_IMAGE            32773
#define ID_BUTTON_VIEW_FRONT            32774
#define ID_BUTTON_VIEW_REAR             32775
#define ID_BUTTON_VIEW_LEFT             32776
#define ID_BUTTON_VIEW_RIGHT            32777
#define ID_BUTTON_VIEW_TOP              32778
#define ID_BUTTON_VIEW_BOTTOM           32779
#define ID_BUTTON_VIEW_ISO              32780
#define ID_BUTTON_VIEW_PERSPECTIVE      32781
#define ID_BUTTON_VIEW_ORTHO            32782
#define ID_CONVERT_TO_IGES              32783
#define ID_BUTTON_PRINCIPAL_DIMENSIONS  32784
#define ID_BUTTON_ICE_DATA              32785
#define ID_BUTTON_RESISTANCE_EQUATIONS  32786
#define ID_BUTTON_IMPORT_HULL           32787
#define ID_BUTTON_SURFACE_CORRECTIONS   32788
#define ID_BUTTON_Nurbs_Conversion      32789
#define ID_CHECK_BOW_BREAKING           32790
#define ID_CHECK_STERN                  32791
#define ID_BUTTON_DEFINE_SECTIONS       32792
#define ID_BUTTON_CALCULATE_SECTION_POINTS 32793
#define ID_BUTTON_SHOW_HIDE_SECTIONS    32794
#define ID_BUTTON_SHOW_HIDE_SECTION_CUT 32795
#define ID_SPIN_BOW_DRAFT               32796
#define ID_SPIN_STERN_DRAFT             32797
#define ID_CHECK_HIDE_SHOW_WATERLINES   32798
#define ID_CHECK_NO_TRIM                32799
#define ID_BUTTON_APPLY_GENERATION      32800
#define ID_BUTTON_SHOW_HIDE_WATERLINE_CUT 32801
#define ID_EDIT_START                   32802
#define ID_EDIT_END                     32803
#define ID_EDIT_SPACE                   32804
#define ID_EDIT_POINT_GAP               32805
#define ID_BUTTON_HIDE_SHOW_WATERLINES  32806
#define ID_BUTTON_HULL_TRANS            32807
#define ID_BUTTON_HULL_ROTATE           32808
#define ID_BUTTON_SECTION_ROTATE        32809
#define ID_BUTTON_WATERLINE_TRANSLATE   32810
#define ID_BUTTON_WATERLINE_ROTATE      32811
#define ID_SPIN_SECTION_Y               32812
#define ID_SPIN_SECTION_Z               32813
#define ID_SPIN_WATERLINE_Z             32814
#define ID_SPIN_WATERLINE_X             32815
#define ID_SPIN_WATERLINE_Y             32816
#define ID_SPIN_HULL_X_POS              32817
#define ID_SPIN_HULL_Y_POS              32818
#define ID_SPIN_HULL_Z_POS              32819
#define ID_BUTTON_HULL_POINT_TO_POINT   32820
#define ID_SPIN_HULL_X_ANGLE            32821
#define ID_SPIN_HULL_Y_ANGLE            32822
#define ID_SPIN_HULL_Z_Angle            32823
#define ID_BUTTON_SAVE_HULL             32824
#define ID_BUTTON_ANALYSIS              32825
#define ID_BUTTON_SELECT_SECTION        32826
#define ID_SPIN_SECTION_X               32827
#define ID_CHECK_DISTANCE_FOR_AXIS      32828
#define ID_CHECK_DISTANCE               32829
#define ID_CHECK_NUMBER                 32830
#define ID_EDIT_DISTANCE                32831
#define ID_EDIT_NUMBER                  32832
#define ID_EDIT_START_WATERLINE         32833
#define ID_EDIT_END_WATERLINE           32834
#define ID_EDIT_SPACE_WATERLINE         32835
#define ID_CHECK_DISTANCE_WATERLINE     32836
#define ID_CHECK_NUMBER_WATERLINE       32837
#define ID_EDIT_DISTANCE_WATERLINE      32838
#define ID_EDIT_NUMBER_WATERLINE        32839
#define ID_BUTTON_DEFINE                32840
#define ID_VIEW_TOOLBAR1                32841
#define ID_BUTTON_VIEW_ALL              32842
#define IDC_STATIC_INC_THICK            32843
#define IDC_STATIC_INI_SHIP_SPEED       32844
#define ID_ANALYSIS_ADD                 32845
#define ID_ANALYSIS1_DELETE             32846
#define ID_ANALYSIS_CLEAR               32847

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        353
#define _APS_NEXT_COMMAND_VALUE         32848
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
