//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// I-RES2.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_IRES2TYPE                   130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDB_BITMAP1                     310
#define IDB_BITMAP2                     311
#define IDD_DIALOG1                     312
#define IDD_DIALOG_SELECT_SECTIONS      312
#define IDC_LIST1                       1000
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTONZoomProg               32771
#define ID_BUTTONZoomWin                32772
#define ID_BUTTONZoomAll                32773
#define ID_BUTTONPan                    32774
#define ID_BUTTONPanGlo                 32775
#define ID_BUTTONRot                    32776
#define ID_BUTTONReset                  32777
#define ID_BUTTONFront                  32778
#define ID_BUTTONTop                    32779
#define ID_BUTTONLeft                   32781
#define ID_BUTTONBack                   32782
#define ID_BUTTONRight                  32783
#define ID_BUTTONBottom                 32784
#define ID_BUTTONAxo                    32785
#define ID_CONVERT_TO_IGES              32786
#define ID_BUTTON_PRINCIPAL_DIMENSIONS  32787
#define ID_BUTTON_ICE_DATA              32788
#define ID_BUTTON_RESISTANCE_EQUATIONS  32789
#define ID_BUTTON_IMPORT_HULL           32790
#define ID_BUTTON_SURFACE_CORRECTIONS   32791
#define ID_BUTTON_Nurbs_Conversion      32792
#define ID_CHECK_BOW_BREAKING           32795
#define ID_CHECK_STERN                  32796
#define ID_BUTTON_DEFINE_SECTIONS       32797
#define ID_BUTTON_CALCULATE_SECTION_POINTS 32798
#define ID_BUTTON_SHOW_HIDE_SECTIONS    32799
#define ID_BUTTON_SHOW_HIDE_SECTION_CUT 32800
#define ID_SPIN_BOW_DRAFT               32801
#define ID_SPIN_STERN_DRAFT             32802
#define ID_CHECK_HIDE_SHOW_WATERLINES   32803
#define ID_CHECK_NO_TRIM                32804
#define ID_BUTTON_APPLY_GENERATION      32805
#define ID_BUTTON_SHOW_HIDE_WATERLINE_CUT 32806
#define ID_EDIT_START                   32807
#define ID_EDIT_END                     32808
#define ID_EDIT_SPACE                   32809
#define ID_EDIT_POINT_GAP               32811
#define ID_BUTTON_HIDE_SHOW_WATERLINES  32813
#define ID_BUTTON_HULL_TRANS            32814
#define ID_BUTTON_HULL_ROTATE           32815
#define ID_BUTTON_SECTION_ROTATE        32816
#define ID_BUTTON_WATERLINE_TRANSLATE   32817
#define ID_BUTTON_WATERLINE_ROTATE      32818
#define ID_SPIN_SECTION_Y               32819
#define ID_SPIN_SECTION_Z               32820
#define ID_SPIN_WATERLINE_Z             32821
#define ID_SPIN_WATERLINE_X             32822
#define ID_SPIN_WATERLINE_Y             32823
#define ID_SPIN_HULL_X_POS              32825
#define ID_SPIN_HULL_Y_POS              32826
#define ID_SPIN_HULL_Z_POS              32827
#define ID_BUTTON_HULL_POINT_TO_POINT   32828
#define ID_SPIN_HULL_X_ANGLE            32829
#define ID_SPIN_HULL_Y_ANGLE            32830
#define ID_SPIN_HULL_Z_Angle            32831
#define ID_BUTTON_SAVE_HULL             32834
#define ID_BUTTON_ANALYSIS              32835
#define ID_BUTTON_SELECT_SECTION        32836
#define ID_SPIN_SECTION_X               32837

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        314
#define _APS_NEXT_COMMAND_VALUE         32838
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
