//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// IRES3.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_IRETYPE                     130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_MAIN_TOOLBAR         310
#define IDB_PNG_NEW                     313
#define IDB_BITMAP_NEW                  317
#define IDB_BITMAP_DATUM                318
#define IDB_BITMAP_NORMAL               319
#define IDB_BITMAP_ROT                  320
#define IDB_BITMAP_TRANS                321
#define IDD_DIALOG_DRAFTSECTION         322
#define IDD_DIALOG_CROSSSECTION         323
#define IDB_BITMAP_CALC                 325
#define IDB_BITMAP_TOOLBAR              326
#define IDR_TOOLBAR1                    329
#define IDB_BITMAP1                     330
#define IDR_TOOLBAR2                    331
#define IDC_MFCBUTTON_CLEAR             1000
#define ID_VIEW_TOOLBAR1                1001
#define IDC_MFCBUTTON_TRANS             1001
#define IDC_CHECK_POINT                 1001
#define IDC_MFCBUTTON_ROT               1002
#define IDC_CHECK_AXIS                  1002
#define IDC_MFCBUTTON_DATUM             1003
#define IDC_EDIT_DRAFT                  1003
#define IDC_MFCBUTTON_NORMAL            1004
#define IDC_EDIT_POINT_DISTANCE         1004
#define IDC_EDIT_AXIS_DISTANCE          1005
#define IDC_MFCBUTTON_CALCULATE         1006
#define IDC_EDIT_DRAFT2                 1007
#define IDC_EDIT_DRAFT3                 1008
#define ID_BUTTON_OPEN                  32771
#define ID_BUTTON_SAVE                  32772
#define ID_BUTTON_SAVE_IMAGE            32773
#define ID_BUTTON_VIEW_FRONT            32774
#define ID_BUTTON_VIEW_REAR             32775
#define ID_BUTTON_VIEW_LEFT             32776
#define ID_BUTTON_VIEW_RIGHT            32777
#define ID_BUTTON_VIEW_TOP              32778
#define ID_BUTTON_VIEW_BOTTOM           32779
#define ID_BUTTON_VIEW_ISO              32780
#define ID_BUTTON_VIEW_PERSPECTIVE      32781
#define ID_BUTTON_VIEW_ORTHO            32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        333
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
